name: 'Build Manuscript'
description: 'Build a manuscript from a repository'

inputs:
  image_version:
    description: "Which RRP image version to use"
    required: true

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v2
    - uses: addnab/docker-run-action@v3
      with: 
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        image: rrp:latest
        run: echo $(ls)
