name: 'Build Manuscript'
description: 'Build a manuscript from a repository'

inputs:
  token:
    description: "A GitHub PAT"
    required: true
  image_version:
    description: "Which RRP image version to use"
    required: true

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v2
    - uses: addnab/docker-run-action@v3
      with: 
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.token }}
        image: ghcr.io/dylanrussellmd/rrp:v${{ inputs.image_version }}
        run: echo $(ls)
